# Generated by Django 6.1.1 on 2026-09-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20260917_0124'),
        ('projects', '0003_auto_20260917_2222'),
    ]

    operations = [
    ]
