# Generated by Django 6.1.1 on 2026-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge_0002_auto_20260917_0124_0003_auto_20260917_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_finished', 'Not finished'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_finished', max_length=20),
        ),
    ]
